### ISSUE TITLE
gofabric8 deploy  —app= no longer works

### ISSUE THREAD

**Issue by rajdavies** [fabric8io/gofabric8#174]
On 0.4.66 - gofabric8 deploy  —app= installs console, templates and CD pipeline whilst previous versions it would only install console + templates. Is there a new way of doing this ?

**Comment by rawlingsj** [comment]
I'm pretty sure it used to still install all the templates but only deploy the console + exposecontroller rather than the full pipeline.  

I just checked here and that's still the case, running:
```
gofabric8 deploy --app=
```
only started the console + exposecontroller pods.  

Just to double check the problem; is is that the CD pipeline templates are being downloaded and added or that the CD pipeline pods are being deployed?

BTW there is a new command that will start minikube with decent default memory and deploy fabric8 to it too.  Also if you only want the console deployed then the whole thing can be done with 
```
gofabric8 start --console
```
Soon it will check that everything is installed too

There's also a new command 
```
gofabric8 console
```

to make it even easier to open up the console on any minishift / minikube / GKE / openshift install

**Comment by rajdavies** [comment]
I have jenkins, gogs, nexus pods running. gofabric8 console just hung for a very long time - so reverted to the old style.

**Comment by rajdavies** [comment]
gofabric8 start --console works very well - so going to close this as its a lot nice than the old way.
