### ISSUE TITLE
minishift service <service-name> invalid url/404

### ISSUE THREAD

**Issue by kameshsampath** [fabric8io/gofabric8#187]
`gofabric8 version`

```
gofabric8, version 0.4.69 (branch: 'master', revision: '46f0e45')
  build date:       '20160917-17:38:31'
  go version:       '1.7.1'
```

minishift version: `0.7.1`

minikube version: `v0.10.0`

when doing minishift service <service-name> takes to the right url and then a redirection happens to a `vagrant.f8` urls resulting in HTTP 404 and when adding hosts entries in `/etc/hosts` throws the the following error in browser

```
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.","state":"http://192.168.64.23:31809/"}
```

i just pulled the latest minishift and then started it. then did gofabric8 -y deploy, post that i tried to do minishift service fabric8 it initial starts going to http://minishift-ip:nodePort/ and then a redirect happens to vagrant.f8:8443 and the get HTTP 404 because of not able to do DNS resolution

```
  ~ oc get pods
NAME                              READY     STATUS    RESTARTS   AGE
docker-registry-1-ibj5g           1/1       Running   1          2h
exposecontroller-1-n0zdu          1/1       Running   1          1h
fabric8-docker-registry-1-31pjy   1/1       Running   2          1h
fabric8-forge-1-2rqqo             1/1       Running   1          1h
fabric8-rlf7j                     1/1       Running   2          1h
gogs-1-llnw9                      1/1       Running   1          1h
jenkins-1-c58g9                   1/1       Running   1          1h
nexus-1-2w5dn                     1/1       Running   1          1h
router-1-qua8f                    1/1       Running   2          2h
➜  ~ ckear
zsh: command not found: ckear
➜  ~ gofabric8 console

Opening URL http://fabric8.vagrant.f8
```

And when the browser opens i get 

```
This site can’t be reached

fabric8.vagrant.f8’s server DNS address could not be found.
Search Google for fabric8 vagrant f8
```

Ref https://github.com/jimmidyson/minishift/issues/95

**Comment by rawlingsj** [comment]
Minishift should be using nodeport and not openshift routes when accessing services via the external URLs.  

So that we don't need to login in and check node name's to work out if we're using minishift, we've changed the logic to use the `~/.kube/config` current-context.  Unfortunately late Friday we found an issue with this approach where`oc login` changes the current-context so when `gofabric8 deploy` runs it thinks we're an openshift cluster rather than minishift and defaults exposecontroller to use routes.

The related issue on minishift is https://github.com/jimmidyson/minishift/issues/94 which we will look into early this week.

I can probably come up with a temporary work around during `gofabric8 deploy` to check the node name as well as current-context, which should mean that we default to nodeport again and services open correctly.    It's not ideal but it would get fabric8 working. 

Another workaround you can try is edit the exposecontroller configmap 
```
oc edit configmap exposecontroller
```
and change the `expose-rule` to use `node-port` rather than `route`

delete the exposecontroller pod so that it starts with the updated config and will update your services to use nodeport.

Next delete any existing routes.
```
oc delete routes --all
```
now 
```
gofabric8 console
```
should open up the console correctly

**Comment by kameshsampath** [comment]
@rawlingsj  that does not help.  I dont basically understand how we get the `gofabric8 console` to return url as `http://fabric8.vagrant.f8` in minishift environment. I guess that should return the IP corresponding to `minishift ip`.  This is what I see in my configmap

```
apiVersion: v1
data:
  domain: vagrant.f8
  expose-rule: node-port
kind: ConfigMap
metadata:
  creationTimestamp: 2016-09-17T12:11:40Z
  labels:
    provider: fabric8.io
  name: exposecontroller
  namespace: default
  resourceVersion: "2650"
  selfLink: /api/v1/namespaces/default/configmaps/exposecontroller
  uid: somehex
```

I did update the configmap as per your previous comment, then deleted the exposcontroller pod and all routes. still when i do `gofabric8 console` it goes to the `vagrant.f8` based url.. wondering thats because of the configmap having `domain: vagrant.f8` should that need to be updated to `minishift ip` ?

**Comment by kameshsampath** [comment]
few more things that was observed: after I do delete and recreate of pods as said above: 

when I do `minishift fabric8 --url` gives me `http://192.168.64.23:31809`  and when i open the url it redirects me back to `https://vagrant.f8:8443/oauth/authorize?client_id=fabric8&response_type=token&state=http%3A%2F%2F192.168.64.23%3A31809%2F&redirect_uri=http%3A%2F%2F192.168.64.23%3A31809%2F`  which results again with the error 
```
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.","state":"http://192.168.64.23:31809/"}
```

**Comment by rawlingsj** [comment]
This has been fixed now that minishift is being detected and we don't think it's a standard openshift install that requires a domain + routes rather than NodePort .  Commit that fixed this is https://github.com/fabric8io/gofabric8/commit/384d0a3b65f1bf1f0abd778afe5c651c0724264b
