### ISSUE TITLE
Do you have a stable version?

### ISSUE THREAD

**Issue by seanzhau** [fabric8io/gofabric8#282]
I'm crazy now, Sometimes I'm not sure which is f8 problem or my problem.

Release so fast and upgrade too much, Can I use it in my production ??

**Comment by jstrachan** [comment]
We release frequently yes; you can pick which version you wish to use though & stick on a specific version if you wish.

We've moved to a single combined versioned package set to make it easier to keep track of versions:
http://central.maven.org/maven2/io/fabric8/platform/packages/fabric8-platform/

So you can pick a version from there and use it via kubectl apply -f if you prefer. We should also support a `-v` argument on `gofabric8 start` see https://github.com/fabric8io/gofabric8/issues/285 - though you can use:

```
gofabric8 deploy -v=1.2.3
```

At some point there will be a commercially supported (for many years) fabric8 product if you want something rock solid. Otherwise if you hit an issue please raise it and we'll do our best to work around it. As you can imagine things are pretty fast moving - docker + kubernetes are moving all the time & we're trying to keep fabric8 as stable as possible. I'm hopeful things can settle down a bit now; we've been through various recent changes (e.g. the new controllers  https://blog.fabric8.io/additional-kubernetes-controllers-from-fabric8-you-can-use-with-your-microservice-3126a2c4c132#.xfi3an81d) or the move to jenkins 2 and the new kubenretes pipeline plugin so we can manage build pods better https://blog.fabric8.io/jenkins-kubernetes-plugin-adds-pipeline-capabilities-2d43f934c580#.uqxhtwv6i) then there's been a few improvements to persistence. Hopefully now the core of fabric8 (console / forge / nexus / jenkins / gogs) keep just getting more and more stable now.

We should also have an auto-upgrade feature soon; so you can use fabric8 with an App Store like UI to see which apps have updates and to opt in to deciding when things get upgraded.
https://github.com/fabric8io/fabric8/issues/6186

**Comment by jstrachan** [comment]
am gonna close this issue for now - please raise more issues about any pending specific issues you have though
