### ISSUE TITLE
Memory limitation through --memory isn't always working

### ISSUE THREAD

**Issue by janzeleny** [fabric8io/gofabric8#312]
Hi guys,
I tried to run gofabric8 start which created a VM that consumed almost all of my RAM (> 6G out of 8G). I shut it down with gofrabric8 stop and then I started it again with limiting the memory size:
gofabric8 start --memory=4096

Unfortunately the VM started with >6G memory consumption again.

Experimenting with this some more, it seems that the --memory has the effect only the first time (maybe not even that, I didn't set it the first time). Once the machine memory size is set, it is kept for the following runs even if overridden by different value given at the next startup. I am able to change the memory size using virt-manager and this changed value is not overridden by --memory the next time I start the cluster. Not sure if that's relevant but my VM driver is kvm. If you need any other information, please let me know.

Thanks,
Jan

**Comment by rawlingsj** [comment]
Ok so I recreated your issue:

`gofabric8 start` uses default memory of 6144M
`gofabric8 stop && gofabric8 start --memory=4096` still results in default memory of 6144M
`minikube delete && gofabric8 start --memory=4096` uses correct reduced memory of 4096M

I'm not sure if this is an issue or expected behaviour when working with minikube or minishift - @jimmidyson what do you think?

If the `--memory` flag cannot be used to change the memory setting once the VM has been created perhaps we should ask for some validation / error message to be given my minishift / minikube?

Either way the current work around would be as above to delete the VM first.

**Comment by jimmidyson** [comment]
It's known behaviour of mini* unfortunately. Minishift is looking to make that a bit more obvious to the user & I'm sure that will be upstreamed to minikube soon afterwards.

**Comment by rawlingsj** [comment]
Thanks @jimmidyson 

@janzeleny if the explanation is ok and the workaround helps can we close this issue?

**Comment by janzeleny** [comment]
I'd suggest one more thing and that's documenting this behavior in [Get Started](https://fabric8.io/guide/getStarted/gofabric8.html#changing-memory-or-cpus) guide. Other than that I'm ok with closing this issue.

Thanks for your help guys,
Jan

**Comment by rawlingsj** [comment]
Thanks @janzeleny good point - done.

**Comment by rawlingsj** [comment]
Site is updated now http://fabric8.io/guide/getStarted/gofabric8.html#changing-memory-or-cpus
