### ISSUE TITLE
how to access the console without a domain?

### ISSUE THREAD

**Issue by Fei-Guang** [fabric8io/gofabric8#95]
hello, i have deployed the fabric8 on a public cloud, the user-guide say that use a URL like http://fabric8.${DOMAIN} where DOMAIN is the domain you used to install fabric8  to access the console  ,
but  i  don't have a registered domain name, how to access it via public floating ip assigned by public  cloud provider?

```
 $ kubectl get service
    NAME                      CLUSTER-IP      EXTERNAL-IP   PORT(S)     AGE
    fabric8                   192.168.3.145                 80/TCP      1d
    fabric8-docker-registry   192.168.3.64                  80/TCP      1d
    fabric8-forge             192.168.3.191                 80/TCP      1d
    gogs                      192.168.3.17                  80/TCP      1d
    gogs-ssh                  192.168.3.198                 22/TCP      1d
    jenkins                   192.168.3.59                  80/TCP      1d
    jenkins-jnlp              192.168.3.9                   50000/TCP   1d
    jenkinshift               192.168.3.42                  80/TCP      1d
    kubernetes                192.168.3.1     <none>        443/TCP     7d
    nexus                     192.168.3.156                 80/TCP      1d

$ kubectl describe service fabric8
Name:                   fabric8
Namespace:              default
Labels:                 expose=true,group=io.fabric8.apps,project=console,provider=fabric8,version=2.2.173
Selector:               expose=true,group=io.fabric8.apps,project=console,provider=fabric8
Type:                   LoadBalancer
IP:                     192.168.3.145
Port:                   <unset> 80/TCP
NodePort:               <unset> 30156/TCP
Endpoints:              172.16.48.3:9090
Session Affinity:       None
No events.

```

http://floating-ip:30156 can't be reached

**Comment by rawlingsj** [comment]
Yeah the docs actually dont explain that sorry!  We've done a little blog that covers the different ways to access services on a cluster https://blog.fabric8.io/accessing-your-applications-on-kubernetes-or-openshift-3e69be0ad3bc#.9wr0yog9s

I'll make sure our docs are updated to cover the relevent bit but rather than using the nodeport as you have above you probably want to create a DNS domain, we use clouflare which is free for this type of use and why we recommend it.

https://www.cloudflare.com/dns/

Once you're able to add a DNS record you need to add two records, and point it to the external ip that is running the nginx-ingress pod.

Here's a screen shot of ours, if this helps I'll get our docs updates straight away.

<img width="1287" alt="screenshot 2016-08-26 07 39 16" src="https://cloud.githubusercontent.com/assets/1457180/17996685/42cd9a0e-6b62-11e6-86a1-fb59f89e963f.png">

**Comment by rawlingsj** [comment]
@Fei-Guang did the comment above help?  Would a better docs around setting up a domain help?

**Comment by rohit-ravikoti** [comment]
Hi, is there a way to do this on google cloud as well?

**Comment by shoaibjdev** [comment]
Hi @rawlingsj , do you got any docs mapping the public ip to the domain mentioned during fabric8 setup. I have got a domain but unsure of how to map the stackpoint.io mentioned in master node to my sub-domain. Please advise.
